# Generated by Django 3.1.3 on 2021-11-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startData', '0003_hs477m0809031355_hs479m0809031355_hs486m0809031355_hs488m0809031355_hs490m0809031355_hs492m080903135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hs228M0809031355',
        ),
        migrations.DeleteModel(
            name='Hs230M0809031355',
        ),
        migrations.DeleteModel(
            name='Hs232M0809031355',
        ),
        migrations.DeleteModel(
            name='Hs273M0809031355',
        ),
        migrations.DeleteModel(
            name='Hs276M0809031355',
        ),
        migrations.DeleteModel(
            name='Hs315M0809031355',
        ),
        migrations.DeleteModel(
            name='Hs339M0809031355',
        ),
        migrations.DeleteModel(
            name='Hs341M0809031355',
        ),
        migrations.DeleteModel(
            name='Hs342M0809031355',
        ),
        migrations.DeleteModel(
            name='Hs476M0809031355',
        ),
        migrations.DeleteModel(
            name='Hs477M0809031355',
        ),
        migrations.DeleteModel(
            name='Hs479M0809031355',
        ),
        migrations.DeleteModel(
            name='Hs486M0809031355',
        ),
        migrations.DeleteModel(
            name='Hs488M0809031355',
        ),
        migrations.DeleteModel(
            name='Hs490M0809031355',
        ),
        migrations.DeleteModel(
            name='Hs492M0809031355',
        ),
    ]
